sudo: required
dist: bionic
language: cpp
compiler:
  - gcc
#  - clang


before_install:
  - sudo apt-get update
  - sudo apt-get install -y libqt4-dev libqwt5-qt4-dev libfftw3-dev libglu1-mesa-dev libasound2-dev libqt4-opengl-dev

script:
  - qmake pitch.pro
  - make
  - mkdir cmake-build; cd cmake-build
  - cmake ..
  - make
#EOF
